//go:build (linux || freebsd || openbsd || netbsd || dragonfly || darwin) && !((freebsd || openbsd || netbsd) && arm64)

package vtui

// Code generated by scripts/generate_keysyms.go; DO NOT EDIT.

// Removed: We now rely on Xutf8LookupString for character mapping.
