package main

import (
	"bufio"
	"fmt"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const (
	urlKeysymdef = "https://cgit.freedesktop.org/xorg/proto/x11proto/plain/keysymdef.h"
	urlXF86      = "https://cgit.freedesktop.org/xorg/proto/x11proto/plain/XF86keysym.h"
	outputName   = "x11_keysym_map_generated.go"
)

func main() {
	// Auto-detect project structure
	outPath := ""
	for _, p := range []string{"f4/libs/vtui/", "libs/vtui/", "./", "../"} {
		if _, err := os.Stat(p + "x11_keys.go"); err == nil {
			outPath = p + outputName
			break
		}
	}

	if outPath == "" {
		fmt.Println("Error: Could not find vtui directory (looking for x11_keys.go). Please run from project root.")
		os.Exit(1)
	}

	fmt.Printf("Generating keysym definitions into %s...\n", outPath)

	mapping := make(map[uint32]rune)

	for _, url := range []string{urlKeysymdef, urlXF86} {
		if err := parseURL(url, mapping); err != nil {
			fmt.Printf("Error parsing %s: %v\n", url, err)
			os.Exit(1)
		}
	}

	generateGoFile(mapping, outPath)
	fmt.Printf("Successfully generated %s with %d mappings.\n", outPath, len(mapping))
}

func parseURL(url string, mapping map[uint32]rune) error {
	client := &http.Client{}
	req, _ := http.NewRequest("GET", url, nil)
	// Emulate wget headers to bypass anti-bot filters
	req.Header.Set("User-Agent", "Wget/1.21.1")
	req.Header.Set("Accept", "*/*")
	req.Header.Set("Accept-Encoding", "identity")
	req.Header.Set("Connection", "Keep-Alive")

	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("HTTP %s", resp.Status)
	}

	scanner := bufio.NewScanner(resp.Body)
	// Ищем: #define XK_name 0xvalue /* U+unicode description */
	re := regexp.MustCompile(`\#define\s+(?:XK_|XF86XK_)([a-zA-Z_0-9]+)\s+0x([0-9a-fA-F]+).*(?:U\+([0-9A-F]{4,6}))`)

	lineCount := 0
	foundInFile := 0
	headerPrinted := false

	for scanner.Scan() {
		line := scanner.Text()
		lineCount++

		if lineCount < 15 && strings.TrimSpace(line) != "" && !headerPrinted {
			fmt.Printf("DEBUG: First line of content from %s: %q\n", url, line)
			headerPrinted = true
		}

		matches := re.FindStringSubmatch(line)
		if len(matches) == 4 {
			kv, _ := strconv.ParseUint(matches[2], 16, 32)
			rv, _ := strconv.ParseUint(matches[3], 16, 32)

			keysym := uint32(kv)
			r := rune(rv)

			// Пропускаем ASCII диапазон (обрабатывается в коде напрямую)
			if keysym >= 0x0020 && keysym <= 0x007e {
				continue
			}

			mapping[keysym] = r
			foundInFile++
		}
	}
	fmt.Printf("Parsed %s: found %d Unicode mappings in %d lines.\n", url, foundInFile, lineCount)
	return scanner.Err()
}

func generateGoFile(mapping map[uint32]rune, path string) {
	f, err := os.Create(path)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "package vtui")
	fmt.Fprintln(f, "// Code generated by scripts/generate_keysyms.go; DO NOT EDIT.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "func init() {")
	fmt.Fprintln(f, "    // Merge generated mappings into the main X11 keysym table")
	fmt.Fprintln(f, "    for k, v := range x11GeneratedKeysyms {")
	fmt.Fprintln(f, "        x11KeysymToRune[k] = v")
	fmt.Fprintln(f, "    }")
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "var x11GeneratedKeysyms = map[uint32]rune{")

	// Сортируем ключи для стабильного вывода
	keys := make([]uint32, 0, len(mapping))
	for k := range mapping {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })

	for _, k := range keys {
		r := mapping[k]
		fmt.Fprintf(f, "    0x%08x: %d, // %q\n", k, r, r)
	}

	fmt.Fprintln(f, "}")
}